CREATE DATABASE api_db;
USE API_DB;

CREATE TABLE datos_api
	(ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FECHA VARCHAR(15) NOT NULL,
    IMAGEN LONGBLOB,
    NOMBRE VARCHAR(30) NOT NULL,
    EXPERIENCIA VARCHAR (15) NOT NULL,
    ID_POKEMON INT NOT NULL,
    ATAQUE INT NOT NULL,
    DEFENSA INT NOT NULL);
    
SELECT * FROM datos_api;